image: adoptopenjdk:8-jdk-hotspot

stages:
    - test

before_script:
  - apt-get update -qy
  - apt-get install -y ant
  - ant -version

testall_job:
  stage: test
  tags:
    - docker 

  script: 
    - ls -R
    - echo "ant test started"
    - ant -f FreeCol/build.xml testall || true
    - ls -R
  
  artifacts:
    paths:
      - /builds/krutik_patel1/cosc442-freecol-final-project/FreeCol/build/report