image: adoptopenjdk:11-jdk-hotspot

stages:
    - build
    - test

before_script:
  - apt-get update -qy
  - apt-get install -y ant
  - ant -version

build_job:
  stage: build
  tags:
    - docker 

  script: 
    - echo "ant compile started"
    - ant -f cosc442-freecol-final-project/FreeCol-master/build.xml compile


test_job:
  stage: test
  tags:
    - docker 

  script: 
    - echo "ant test started"
    - ant -f cosc442-freecol-final-project/FreeCol-master/build.xml testall