image: adoptopenjdk:8-jdk-hotspot

stages:
  - test

before_script:
  - apt-get update -qy
  - apt-get install -y wget unzip
  - wget https://archive.apache.org/dist/ant/binaries/apache-ant-1.10.9-bin.zip
  - unzip apache-ant-1.10.9-bin.zip
  - export ANT_HOME=$PWD/apache-ant-1.10.9
  - export PATH=$ANT_HOME/bin:$PATH
  - ant -version

testall_job:
  stage: test
  tags:
    - docker 

  script:
    - echo "ant testall started"
    - ant -f FreeCol/build.xml testall
  
  artifacts:
    paths:
      - /builds/krutik_patel1/cosc442-freecol-final-project/FreeCol/build/report