image: adoptopenjdk:8-jdk-hotspot

stages:
  - test

before_script:
  - apt-get update -qy
  - apt-get install -y wget unzip
  - wget https://archive.apache.org/dist/ant/binaries/apache-ant-1.10.9-bin.zip
  - unzip apache-ant-1.10.9-bin.zip
  - export ANT_HOME=$PWD/apache-ant-1.10.9
  - export PATH=$ANT_HOME/bin:$PATH
  - ant -version

testall_job:
  stage: test
  tags:
    - docker 

  script:
    - ls -R
    - echo "ant test started"
    - set +e  # Disable automatic exit on error
    - ant -f FreeCol/build.xml testall
    - EXIT_CODE=$?  # Capture the exit code of the previous command
    - ls -R  # Display additional information in the logs
    - set -e  # Enable automatic exit on error
    - exit $EXIT_CODE  # Exit the script with the captured exit code
  
  artifacts:
    paths:
      - /builds/krutik_patel1/cosc442-freecol-final-project/FreeCol/build/report