image: openjdk:latest

before_script:
  - apt-get update -qy
  - apt-get install -y ant

stages:
    - build
    - test


build_job:
  stage: build
  tags:
    - docker 

  script: 
    - echo "Maven compile started"
    - ant compile


test_job:
  stage: test
  tags:
    - docker 

  script: 
    - echo "Maven test started"
    - ant testall