image: adoptopenjdk:8-jdk-hotspot

stages:
    - test

before_script:
  - apt-get update -qy
  - apt-get install -y ant
  - ant -version

testall_job:
  stage: test
  tags:
    - docker 

  script: 
    - echo "ant test started"
    - ant -f FreeCol/build.xml testall